stages:          # список стадий, в каждой стадии есть джобы, которые выполняются парелельно в рамках стадии
  # - build
  # - test
  - deploy

build-static-pages-job:  # название джобы
  image: node:lts
  stage: deploy # название стадии к которой привязана джоба
  cache: # кеш, ключ которого хеш ветки
    key: cache-for-my-task-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  script:
    - yarn install
    - yarn run build
    - cp -a dist/. public/ # папка для GitLab Pages статики должна называться public
    # опционально, можно активировать поддержку gzip с помощью следующей строки:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts: # артефакт это папка которая перейдет в так сказать результат выполнения джобы(например zip)
    paths:
      - public # путь к артефакту должен быть /public для GitLab Pages
#   only:
#     - master
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# примеры джоб

# build-job:   
#   stage: build
#   script:
#     - echo "Compiling the code..."
#     - echo "Compile complete."

# unit-test-job: 
#   stage: test 
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - echo "Code coverage is 90%"

# lint-test-job: 
#   stage: test 
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - echo "No lint issues found."

# deploy-job:   
#   stage: deploy
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
