export enum AccessScopesEnum {
  LOGGED_IN = 'LOGGED_IN',

  CAN_READ_BOOKS = 'CAN_READ_BOOKS',
  CAN_CREATE_BOOKS = 'CAN_CREATE_BOOKS',
  CAN_EDIT_BOOKS = 'CAN_EDIT_BOOKS',
  CAN_DELETE_BOOKS = 'CAN_DELETE_BOOKS',

  CAN_READ_CARS = 'CAN_READ_CARS',
  CAN_CREATE_CARS = 'CAN_CREATE_CARS',
  CAN_EDIT_CARS = 'CAN_EDIT_CARS',
  CAN_DELETE_CARS = 'CAN_DELETE_CARS'
}
